project:
  type: website


website:
  title: "LinCSS"
  navbar:
    search: false
    right:
      - href: index.qmd
        text: Home
        icon: "bi bi-house"
      - href: news.qmd
        text: News
        icon: "bi bi-calendar-event"
      - href: board.qmd
        text: Board
        icon: "bi bi-people-fill"
      - text: "Guides"
        icon: "bi bi-file-earmark-text"
        menu:
          - href: "guides/arrival.qmd"
            text: Arrival
          - href: "guides/internship.qmd"
            text: Internship
      - href: membership.qmd
        text: "Become a Member!"
        icon: "bi bi-pencil-square"
      #- href: about.qmd
      #  text: About
      #  icon: "bi-info-circle"
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com

  page-footer: 
    border: false
    left:  <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><span property="dct:title">This Website</span> by <span property="cc:attributionName">LinCSS</span> is licensed under <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a></p>  



format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: false