---
title: Internship Guide
author: Marc Sparhuber
date: 2025-01-27

format:
  html:
    toc: true
---

# A short guide on how to find a research internship (and other info about the 3rd semester)

Dear reader,

Perhaps you’ve been thinking about taking the [research internship course](https://drive.google.com/file/d/1HR49ardZ_WVtmuXsNIA7dx2XFKfzAf4k/view?usp=drive_link) (please check if up-to-date) in the third semester. If so, I’m here to give you some advice that I hope may be helpful to you. If not, maybe this will convince you to reconsider\!

Why do a research internship? There are many reasons, such as:

- Wanting to try out “real” research.

- Trying to get your foot in the door in a research niche you find interesting.

- Getting out of doing one of the courses from semester 3 (totally valid reason).

- Finding someone to do your master’s thesis with that’s not from IAS (very reasonable and valid if your research interests do not align with what IAS has to offer).

- Wanting to do an internship at a company/organization but having trouble navigating the Swedish job market (it *is* difficult).

- Doing it for your CV.

(I want to highlight at this point that there is a small number of students of the current and previous cohorts who signed up for a research internship or tried to (but were too late) to avoid doing the last course in semester 3\. I think that considering an internship early may give you a wider range of possible positions and avoids disappointment if you’re pressed for time at the end.)

So how do you find an internship supervisor? For this guide I will assume that you’re interested in a research niche that is not offered at IAS – that’s because you can apply the following “methods” to IAS members as well but don’t really need to (since you can just talk to them or find out more about them by checking their profile).

So, let’s say that over the course of your studies you’ve sort of become interested – broadly – in *protest participation and social media* (just an example to work with). Let’s also say that you do not have a specific paper that sparked that interest (if you do, that’s great and you can go to step 2.) My advice for you would be to try the following steps:

## 1. Finding a starting point for your search

My first step would be to search papers on google scholar. Use different terms to search for your interest (“protest participation twitter”), think of specific cases if applicable (“protest George Floyd social media”), think of methods that you find interesting or want to use (“protests social media network analysis”). For now, just have a look at what you find, open papers you find interesting in another tab, read their abstracts and if interesting, keep them for later.

## 2. Going deeper

Of these, select one or a handful of the most interesting papers. Then, and I think this is quite important, check their dates. This is because from my experience researchers don’t have the freedom to always just research the exact topic, they are interested in but are bound to grants etc. Also, sometimes they just change their personal interests over time. So ideally you want to find people among the authors of these papers who, when you check their more recent publications, still do research you are interested in. If you find a paper that’s maybe 5 years old or so and the authors have moved on to another topic then check who has cited this paper. In general, this is a very good way to find current researchers on a topic. You could, and I think should, also do this for the other papers you are interested in. This way, over time, you will find the names of people who are active in this field, authors that keep publishing in this field. Write these names down somewhere. If you feel like going even deeper, you can use websites such as semantic scholar to look up researchers of interest and dig through the tabs “Citing Authors”, “Referenced Authors” and “Co-Authors” to find more potential supervisors. Google scholar has a similar functionality, when you go on someone’s profile you can check their Co-Authors. Another interesting thing you can do within Google Scholar is to use the self-assigned tag system. Any researcher ([example](https://scholar.google.com/citations?user=OgRohLcAAAAJ&hl=de&oi=ao)) who has created a Scholar profile for themselves has the option to assign themselves tags. When you click this, you get to a list of all people who have assigned themselves this tag. You can even combine them if you’re looking for a combination of tags such as this “label:social\_networks \+ label:quantitative\_methods”, you can even add locations (indirectly) like this label:social\_networks \+ label:quantitative\_methods ".se" (“.edu” for US, “.ac.uk” for UK, etc.).

## 3. Getting an idea of the field’s landscape

Now you have likely got a few researchers that you can identify as experts in their field. At this point, you can check them out more thoroughly:

- Where do they work and as part of what faculty/department?

- Do they seem nice? (I know this is a bit difficult to assess but you could check their website and social media to maybe get an idea)

- What’s their position? (Are they post-docs, professors or even PhD students?)

Based on this information and their publication history I’m sure you can create a bit of an ordered list of preferences. From personal experience (no clue if this is generalizable) I have these comments: The “lower” in the research hierarchy, i.e., PhD students, new post-docs, the more involved in the actual research process you can expect to get, whereas with professors, I think they might make you do busy work that they don’t want to do themselves more frequently but their connections in the research world are often better.

With these things in mind, think more about who you would like to work with and how? Did you find someone in Sweden? If so, would you consider visiting there every once in a while or even move there for the internship? Think about time zones and working remotely.

## 4. Timing

You can technically do your internship anytime, as long as the course coordinator for the internship (currently Carl, might change), and your internship supervisor agree on it. That being said, there are times during the year when it would be more advantageous to do so. This also depends on what your priorities are – what courses you would like to take or not take during the third semester (more on that later). I’m also assuming you don’t want to sacrifice your holidays (too much). Keep in mind that the internship requires 5 weeks full-time work (approximately 40 hours per week), which include the writing of the internship report. These are common approaches to timing your internship:

- Do it when you would have otherwise taken the course you’re replacing it with. This is nice because you use as little extra time as possible but can be difficult to arrange.  
- Take a small amount of holidays (summer or winter) and the course that’s happening at that time (so first or last of the 3rd semester) as your time for the internship. This is a bit more chill and allows you to not have to do it full-time.  
- If you’re doing it remotely or in Norrköping you might also want to think about doing it alongside the other courses in semester 3 and working less than or part-time.

Many students also use the internship to slowly start working on a thesis topic. Though for this it can be useful to do it just before the thesis begins (replacing the last course of the 3rd semester), if you already have an idea or your potential supervisor is up for it, you can also start working on it in the summer.

## 5. Drafting an application

I forgot to mention this so far but the goal of this is not to find a paid or advertised position. The goal is to get where you want to be. For this reason, I recommend to directly message the person you want to work with, with a cover letter in the email’s body and CV and grades attached. If you want a sample cover letter that I have used to get research internships in the past, feel free to contact [me](mailto:marc.sparhuber@gmail.com).

For your application and cover letter, my first tip would be: Don’t sell yourself short\! I know students within the CSS master’s sometimes talk about how we don’t learn enough “advanced” things, or you might worry that you haven’t done this or that course yet. BUT consider this: there are a lot of people in the space of the social and behavioral sciences that only use SPSS (statistical software a la drag and drop) or are noobs at R. You’re probably already an above-average R user at this point just after 1-2 semesters. This makes you very valuable to just about any research lab in the social and behavioral sciences. You should highlight your skills and how useful this makes you.

Secondly, I would like to point out that researchers, due to the profession being kind of insular, are (in my opinion) sometimes a bit starved for genuine interest and appreciation of the thing they are passionate about. Use this\! Show that you are interested, refer to their papers and they will like you already before you meet them.

Thirdly, you are (in most cases) free labor for them which is great for them, often there is no reason for them not to take you in, as long as they have something you can work for them on.

If you keep these things in mind, mention your proficiencies and previous experiences I think your chances are pretty good. For more tips, especially regarding Swedish work culture, please refer to Jonna Ljungblad’s [presentation](https://docs.google.com/presentation/d/18Wpk9RejgaifK9ykJnRvb54jPoEiEe8r/edit?usp=sharing&ouid=105504359834695450892&rtpof=true&sd=true) and [CV template](https://docs.google.com/document/d/1j2QtxdhG1_bVXYCmhgX81uyPvlRU-wNP/edit?usp=sharing&ouid=105504359834695450892&rtpof=true&sd=true).

## 6. Money

As I said in the part above you’re likely not gonna get paid. But there is a way to potentially definitely get paid: [Erasmus \+ Traineeships](https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/traineeships-abroad-for-students). As long as you are a student (or recent graduate) of any Uni with an Erasmus \+ Charter (pretty much all, including LiU), your planned internship is between 2 and 12 months long, you are willing to go to the physical location of your internship for at least 5 days of your internship duration, and you don’t mind working full-time (at least on paper), you can get paid a variable amount of Euros depending on which country your internship is located. This is usually 500-700 Euro per month. Importantly, the country of your internship cannot be Sweden but it can be your home country (as long as it is part of the Erasmus+ framework.

As you may have noticed, this makes it necessary to do an internship that is longer than needed by the standards laid out by the [Study Guide](https://drive.google.com/file/d/1HR49ardZ_WVtmuXsNIA7dx2XFKfzAf4k/view?usp=drive_link). I believe that it’s worth considering, as this is relatively “easy” money, especially if you’re doing your internship remotely.

For more information on this, please refer to the presentation that you received for potential exchanges. You will have to clear this with the internship supervisor and the responsible exchange people at LiU.

## 7. A little more on what to do in Semester 3

As IAS is planning on reworking the courses offered in the third semester (when this guide is published), please make sure to double check if the information in this part of the guide is still accurate. 
Apart from the internship you can do to replace one of the courses in the 3rd semester, you can also replace further courses with courses from other universities (or even previous studies). This is especially handy if courses are offered that don’t seem interesting to you or you want to take a specific course in a field that is not offered here by IAS.

Before giving advice on such courses we want to mention the following general rule of thumb: No MOOCs (even if they award ECTS and are structured more like distance courses), not more than 15 ECTS programming, not more than 15 ECTS social science. But, distance courses are generally allowed (especially if offered in Sweden). Also, it might be relevant to know that you can take courses from Bachelor level (though you have to discuss this more closely with the responsible people). Though I don’t remember asking about this, summer schools that award ECTS may be accredited too.

This leaves us with a couple of ways to search for courses:

- First and foremost, [universityadmissions.se](http://universityadmissions.se). Here you can filter by semester, level, date, field, etc.   
- Courses offered through [ECIU](https://www.eciu.eu/), which LiU is a member of.  
- Some universities might not list (all of) their courses on universityadmissions, so it can be useful to just search “freestanding courses Uni X, field Y”, etc. One example of this would be [this](https://www.psy.lu.se/en/education/study-psychology-0/study-freestanding-courses).  
- Other online university courses offered by universities across the world.

So far, I believe most students that have taken courses from outside LiU, have opted for distance programming courses, some of these are:

- [Introduction to relational databases](https://www.du.se/en/study-at-du/kurser/course/?code=GIK23M): This course is instructive if you want to learn about SQL and databases and offers a very friendly work-load, as well as flexible deadlines. In case your application is dismissed some students were able to get in after a few emails with the people respondible for admission.  
- [Programming in Python](https://www.kth.se/student/kurser/kurs/BB1000?l=en): This course is from KTH in Stockholm and is conducted via distance so there are online zoom lectures and labs (no attendance required and also recorded). It gives an introduction to python starting from 0 and is a good way to learn python and git\! work. The course lasts three months and there are three assignments that determine your grade.   
- [Python \- a Gateway to Machine Learning](https://www.hh.se/english/education/courses/python---a-gateway-to-machine-learning.html): Also a python course providing a general introduction to programming in python and then focusing on machine learning.   
- [Machine Learning](https://engage.eciu.eu/challenges/7916119c-7bb7-4703-9d12-8c56bfc8dc98/machine-learning): This course is from Dublin University and conducted via the [ECIU platform](https://engage.eciu.eu/) so it is free for international students as well. The course is an introduction to machine learning in python so it assumes that you have a basic understanding of python. It takes place every year from January \- April but you need to apply by December.       
- [Ethics of AI:](https://engage.eciu.eu/micro-modules/5c1f9bbe-b94b-43d3-909b-15e884f4c34c/ethics-of-artificial-intelligence) This course is also conducted by LiU and you can apply via the [ECIU platform](https://engage.eciu.eu/) (important if you are an international student and you do not want to pay course fees) or university admissions. The course takes place both in autumn AND summer and covers philosophical concepts regarding the use of AI systems. It is very similar to the Data and Big Ethics course if you are interested in these topics.   
- [Programming in C\#](https://mau.se/en/study-education/course/da204e/) if you want to learn “real” programming lol

Important information about applying through universityadmissions:

- ***START EARLY:*** The deadlines for applying for fall semester courses are very early. You might be too late if you start looking in April.  
- If you are an international student you have to take into account the course fees. You will likely have to pay additional costs for the course and will not be reimbursed for the course you take less through the IAS.  
- Feel free to apply to more courses than you can take. You can always drop them later and you might not get accepted for all you apply for.

I think that about wraps it up. If you have any questions, want advice, or think that there’s something missing here please don’t hesitate to contact us :) 

Sincerely, and wishing you the best of luck,

LinCSS
